config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # CRUD ACTIONS

  # As user: I can see all the restaurans
  get '/restaurants', to: 'restaurants#index'

  # As a user: I can creat a restaurant
  get '/restaurants/new', to: 'restaurants#new', as: :new_restaurant # criar o formulario
  post '/restaurants', to: 'restaurants#create' # criar o restaurnte

  # As a user: I can edit a restaurant
  get '/restaurants/:id/edit', to: 'restaurants#edit', as: :edit_restaurant
  patch '/restaurants/:id', to: 'restaurants#update'

  # As a user: I can delete a restaurant
  delete '/restaurants/:id', to: 'restaurants#destroy', as: :delete_restaurant

  # As user: I can see specific information about one restaurant
  get '/restaurants/:id', to: 'restaurants#show', as: :restaurant
end

# Rails.application.routes.draw do
#   resources :restaurants
# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :rating, inclusion: { in: 1..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
    # @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new # para renderizar o form_for
  end

  def create # nao tem view... tem que redirecionar para alguma pagina
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save

    redirect_to restaurant_path(@restaurant)
  end

  def edit
    # @restaurant = Restaurant.find(params[:id])
  end

  def update # nao tem view... tem que redirecionar para alguma pagina
    # @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)

    redirect_to restaurant_path(@restaurant)
  end

  def destroy # nao tem view
    # @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThespoonWithActiverecord</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class="container p-4">
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end -%>
</div>

app/views/restaurants/edit.html.erb
<%= render 'form' %>

app/views/restaurants/index.html.erb
<h1>Check our restaurants!</h1>
<%= link_to 'Inserir Restaurante', new_restaurant_path %>
<br><br>

  <% @restaurants.each do |restaurant| %>
    <p> Id: <strong><%=restaurant.id %></strong> </p>
    <p> Name: <%= link_to restaurant.name, restaurant_path(restaurant) %> </p>
    <p> Rating: <%= restaurant.rating %> </p>
    <br>
  <% end -%>

app/views/restaurants/new.html.erb
<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1> <%= @restaurant.name %> </h1>
<h2> <%= @restaurant.rating %> stars </h2>
<h3> <%= @restaurant.address %></h3>

<!-- app/views/restaurants/show.html.erb -->
<%= link_to "Delete #{@restaurant.name}",
            restaurant_path(@restaurant),
            method: :delete,
            data: { confirm: "Are you sure?" } %>

<%= link_to "Edit", edit_restaurant_path(@restaurant) %>
<%= link_to "Voltar", restaurants_path %>